### ISSUE TITLE
Inserir Quadro de Conhecimentos 1

### ISSUE THREAD

**Issue by gabrielapivetta** [fga-eps-mds/2022.2-Amis-Doc#10]
**Descrição:**

Criar o Quadro de Conhecimentos dos integrantes antes de iniciar o desenvolvimento do projeto.

**Tasks**
- [x] Montar o Quadro de Conhecimentos
- [x] Enviar para os integrantes preencherem
- [x] Introdução do documento

**Critérios de aceitação:**
- [x] Todos os integrantes devem preencher o quadro
