### ISSUE TITLE
Ampliação de testes do front de páginas do front

### ISSUE THREAD

**Issue by paulohborba** [fga-eps-mds/2022.2-Amis-Doc#118]
**Descrição:**

Aqui vc vai descrever o que tem para ser feito e um pouco do contexto da issue

**Tasks**
- [ ] Ampliar os Testes na página de turmas
- [ ] Ampliar os Testes na página de assistentes
- [ ] Ampliar os Testes na página de receitas

**Critérios de aceitação:**
- [ ] Cobertura de Testes
