### ISSUE TITLE
Slides

### ISSUE THREAD

**Issue by Jvsoutomaior** [fga-eps-mds/2022.2-Amis-Doc#120]
**Descrição:**

Criação de slides para apresentação final abordando os seguintes topicos:
- Apresentação da visão do produto e canvas MVP (introdução)
- Escopo, Custo e Tempo do projeto. Monitoramento e análise das relações dessas áreas em função dos custos do desenvolvimento do produto.
- Arquitetura
- Gerência de Configuração + DevOps(repositórios, políticas de contribuição, docker, pipelines de CI+CD)
- Riscos (execução e monitoramento)
- Pessoas (quadro de conhecimentos, organização e comunicação do time, ao longo do desenvolvimento)
- Qualidade:
1. estes automatizados(cobertura entra aqui) e de aceitação
2. qualidade do produto de software discutida na abordagem de Analytics
**Observações gerais:**
- como o produto desenvolvido contribui para a solução do problema identificado? Validação das hipóteses de negócio definidas no Canvas MVP considerando, a última versão do produto disponibilizada;
- as diferenças entre o PLANEJADO X REALIZADO e observada em diferentes versões(major) entregues: R1; MVP e RN(última). Essas diferenças precisam ser evidenciadas por meio de dados, tabelas, gráficos, suas explicações e análises, considerando: pessoas, escopo, custo, tempo, riscos e qualidade.
- os defeitos registrados, além das mudanças solicitadas, que não foram possíveis de serem atendidas. 
- a execução dos pipelines de CI e CD, explicando a orquestração e destacando alguns dados: a qtde de vezes que o pipeline foi executado; a qtde de vezes que ele “quebrou”, quantos PRs foram abertos X fechados; qtde releases geradas; qtde de releases implantadas (ambiente de homologação)
- respostas às questões relacionadas a qualidade do produto e atividades de analytics. Na apresentação, não é necessário entrar em detalhes sobre as análises estatísticas descritas no notebook. Na perspectiva dos usuários, o importante é apresentar essa parte do escopo(não-funcional) e dar visibilidade à estruturação para observação da qualidade do produto  em algumas subcaracteristicas relacionadas às caraterísticas de facilidade de manutenção e confiabilidade. - reforçando esse apontamento feito na entrega da 1a. release. A apresentação da arquitetura precisa contemplar o diagrama de relações dos microsserviços, tecnologias e dispositivos, além das visões do sistema: lógica; implantação; processos e dados(DER + MER). A visão de implantação considera os aspectos da gerencia de configuração.
- o escopo do projeto contempla o esforço empreendido nas fases de iniciação e planejamento, além dos esforços de desenvolvimento e gerenciamento do backlog do produto

**Tasks**
- [ ] Criar paginas de slides
- [ ] Definir o que cada um ira falar na ultima apresentação

**Critérios de aceitação:**
- [ ] Slides prontos para apresentação
