### ISSUE TITLE
[DOC] Evolução de Risco 

### ISSUE THREAD

**Issue by CaioSulz** [fga-eps-mds/2022.2-Amis-Doc#123]
**Descrição:**

Evolução do Documento de Risco, pós Release 1

**Tasks**

- [ ]  Relacionar risco com o tempo
- [ ] Evolução do documento em geral

**Critérios de aceitação:**
- [ ] Tornar imagens ou markdown estáticos em planilha dinâmica, caso exista
