### ISSUE TITLE
Documentação do MVP

### ISSUE THREAD

**Issue by fxred** [fga-eps-mds/2022.2-Amis-Doc#124]
**Descrição:**

Criar documento de entrega da Release 2 (MVP)

**Tasks**

- [x]  Mostrar o Planejado x Entregue
- [x] Mostrar todas as US's que foram entregues
- [x] Mostrar todas as US's que não foram entregues

**Critérios de aceitação:**
- [x] Tornar imagens ou markdown estáticos em planilha dinâmica, caso exista
