### ISSUE TITLE
Documentação do Lean Inception

### ISSUE THREAD

**Issue by gabrielapivetta** [fga-eps-mds/2022.2-Amis-Doc#14]
**Descrição:**

Documentação dos processos do Lean Inception para chegar ao Produto Viável Mínimo (MVP) do projeto.

**Tasks**
- [x] Subir todos os diagramas com explicação

**Critérios de aceitação:**
- [x] Introdução
- [x] Visão de Produto
- [x] O produto É - NÃO É - FAZ - NÃO FAZ
- [x] Objetivos de Negócio
- [x] Personas
- [x] Jornada do Usuário
- [x] Brainstorming de Funcionalidades
- [x] Revisão Técnica, de Negócio e UX
- [x] Sequenciador
- [x] MVP Canvas
