### ISSUE TITLE
Backlog do Produto

### ISSUE THREAD

**Issue by gabrielapivetta** [fga-eps-mds/2022.2-Amis-Doc#15]
**Descrição:**

Desenvolver o Backlog com as histórias de usuário, features e épicos dos requisitos do produto.

**Tasks**
- [x] Listar as histórias de usuário
- [x] Separar as histórias de usuário em features
- [x] Separar as features em épicos

**Critérios de aceitação:**
- [x] Introdução
- [x] Tebela com histórias de usuário, features e épicos.

**Comment by andrelucasf** [comment]
Primeira versão do backlog finalizada no dia 20/11/2022.
