### ISSUE TITLE
Configurar SonarQube Backend

### ISSUE THREAD

**Issue by jps12** [fga-eps-mds/2022.2-Amis-Doc#21]
**Descrição:**

Configurar a integração com os repositórios do github. 

**Tasks**
- [x] Configurar integração com o backend
- [x] Listar as métricas que serão usadas
- [x] Gerar as métricas das pipelines

**Critérios de aceitação:**
- [x] As pipelines configuradas gerando as métricas
- [x] As pipelines ativadas por commits para o CI/CD

**Comment by thiagolsg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Amis-6360797e8fcdf43062d4d7b8/issues/fga-eps-mds/2022.2-Amis-Doc/21?planning-poker) with Zenhub @andrelucasf @jps12 @gabrielapivetta @KalebeLopes @Jvsoutomaior @fxred @CaioSulz @ItaloBrunoM @FabricioDeQueiroz @paulohborba

**Comment by jps12** [comment]
@gabrielapivetta @KalebeLopes Issue aberta para revisão. Os commits referentes a essa issue foram feitos diretamente na main devido às especificidades do problema a ser resolvido.

**Comment by thiagolsg** [comment]
Commits relacionados a essa issue

https://github.com/fga-eps-mds/2022.2-Amis-Service/commit/4b018866d19b5f74dc0550c710b1b1f9670b339e
https://github.com/fga-eps-mds/2022.2-Amis-Service/commit/e866446320980500ad809918bfac56bca4a9d3be
https://github.com/fga-eps-mds/2022.2-Amis-Service/commit/d6f06b4215a3e01b1e8a44905bd6f072b241010f
https://github.com/fga-eps-mds/2022.2-Amis-Service/commit/7294c26fd405b300babd157eb002b26eae003f9a
https://github.com/fga-eps-mds/2022.2-Amis-Service/commit/d3c3db6fdebf497176a7979ccba6d7ac072b6bc9
https://github.com/fga-eps-mds/2022.2-Amis-Service/commit/05e25482bff072dedffcf1eecaa5136eeb14a77e
https://github.com/fga-eps-mds/2022.2-Amis-Service/commit/f1a9b513521e277b8472b00b3b766de6ba166b0b
