### ISSUE TITLE
Documento de arquitetura

### ISSUE THREAD

**Issue by jps12** [fga-eps-mds/2022.2-Amis-Doc#28]
**Descrição:**

Criar o documento de arquitetura visando esclarecer os principais pontos sobre a arquitetura escolhida 

**Tasks**
- [x] Listar tecnologias a serem usadas e explicar sobre cada uma.
- [x] Ambiente de desenvolvimento.
- [x] Listar arquiteturas e padrões a serem usados.
- [x] Desenhar os diagramas

**Critérios de aceitação:**
- [x] Documento consegue passar uma ideia completa sobre a arquitetura utilizada
