### ISSUE TITLE
Guia de contribuição

### ISSUE THREAD

**Issue by jps12** [fga-eps-mds/2022.2-Amis-Doc#29]
**Descrição:**

Criar um guia para contribuição no github explicando quais passos devem ser seguidos para contribuir nos repositórios

**Tasks**
- [x] Explicar padrões de commit
- [x] Explicar padrões de issues
- [x] Explicar padrões de pull requests
- [x] Explicar padrões de branchs
- [ ] Configurar templates de issues e PR em todos os repositórios

**Critérios de aceitação:**
- [x] Guia de contribuição claro e conciso
- [ ] templates configurados de pr e issues
