### ISSUE TITLE
Documento de custo

### ISSUE THREAD

**Issue by jps12** [fga-eps-mds/2022.2-Amis-Doc#30]
**Descrição:**

Calcular o custo do projeto.

**Tasks**
- [x] Estimar gastos do projeto
- [x] Montar tabelas
- [x] Pesquisar dados reais

**Critérios de aceitação:**
- [x] O documento passa uma visão geral do custo do projeto
- [x] Apresentar explicações sobre os gastos da equipe
