### ISSUE TITLE
Protótipo de alta fidelidade

### ISSUE THREAD

**Issue by jps12** [fga-eps-mds/2022.2-Amis-Doc#31]
## **Descrição:**

Desenvolver e documentar o protótipo de alta fidelidade do projeto.

## **Tasks**
- [x] Reunir telas do protótipo
- [x] Criar documento com breve explicação do protótipo existente
- [x] Cria novas telas e adicionar ao documento

## **Critérios de aceitação:**
- [x] Documento ilustrativo e descritivo sobre o protótipo.

**Comment by andrelucasf** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Amis-6360797e8fcdf43062d4d7b8/issues/fga-eps-mds/2022.2-Amis-Doc/31?planning-poker) with Zenhub @CaioSulz @FabricioDeQueiroz @fxred @gabrielapivetta @ItaloBrunoM @jps12 @Jvsoutomaior @KalebeLopes @paulohborba @thiagolsg
