### ISSUE TITLE
Configuração do ambiente de Homologação

### ISSUE THREAD

**Issue by thiagolsg** [fga-eps-mds/2022.2-Amis-Doc#37]
**Descrição:**

Esta tarefa é para configuração do ambiente onde será feito o deploy das aplicações.

**Tasks**
- [x] Definir a melhor solução
- [x] Fazer o deploy do ambiente backend para homologação
- [x] Fazer o deploy contínuo do ambiente frontend para homologação

**Critérios de aceitação:**
- [x] Disponibilizar o endereço do frontend
- [x] Disponibilizar o endereço do backend
- [x] Acesso dos ambientes em homologação

**Comment by andrelucasf** [comment]
Deploy continuo do ambiente de homologação do frontend realizado pelo Azure e disponível no endereço: https://gentle-hill-0c05e9510.2.azurestaticapps.net/

**Comment by jps12** [comment]
Deploy continuo configurado e a api está disponível no endereço:
https://amis-service-stg.azurewebsites.net/api/hello_world

**Comment by jps12** [comment]
Essa issue não possui PR pois não tme entregável nos repositórios
