### ISSUE TITLE
Dojo em Docker

### ISSUE THREAD

**Issue by jps12** [fga-eps-mds/2022.2-Amis-Doc#4]
**Descrição:**

Criar um dojo sobre docker para explicar os fundamentos e funcionamento do docker e docker compose.

**Tasks**
- [x] Agendar horário para realização do dojo
- [x] Realizar o dojo
- [x] Gravar o Dojo

**Critérios de aceitação:**
- [x] O dojo foi transmitido e gravado para ser acessível posteriormente
- [x] Foram passados os principais fundamentos de docker

**Comment by jps12** [comment]
Issue concluída
