### ISSUE TITLE
RoadMap

### ISSUE THREAD

**Issue by thiagolsg** [fga-eps-mds/2022.2-Amis-Doc#49]
**Descrição:**

O roadmap é um diagrama que mostra de maneira mais visual a estimativa de tempo teremos com relação ao projeto. Tendo isso em vista é importante a execução desse diagrama para mostrar de maneira mais visual qual é o planejamento da equipe quanto ao tempo do projeto.

**Tasks**
- [x] Escrever issues com base nas Histórias de Usuário no documento de backlog do produto
- [x] Agrupar as issues em épicos usando a ferramenta do Zenhub
- [x] Estimar quanto tempo cada épico vai durar na aba de RoadMap no ZenHub

**Critérios de aceitação:**
- [x] Roadmap criado e coerente com o tempo estimado para cada US.

Obs: Essa issue não terá PR aberto

**Comment by andrelucasf** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Amis-6360797e8fcdf43062d4d7b8/issues/fga-eps-mds/2022.2-Amis-Doc/49?planning-poker) with Zenhub @jps12 @thiagolsg @gabrielapivetta @KalebeLopes @ItaloBrunoM @FabricioDeQueiroz @Jvsoutomaior @paulohborba @CaioSulz @fxred

**Comment by jps12** [comment]
https://app.zenhub.com/workspaces/amis-6360797e8fcdf43062d4d7b8/roadmap -> Fizemos o Roadmap nesse link fazendo os Épicos de acordo com o [Product Backlog](https://fga-eps-mds.github.io/2022.2-Amis-Doc/Backlog/backlog/).

**Comment by thiagolsg** [comment]
Ficou muito bom e coerente com o backlog e suas prioridades
