### ISSUE TITLE
Documento de Risco

### ISSUE THREAD

**Issue by thiagolsg** [fga-eps-mds/2022.2-Amis-Doc#50]
**Descrição:**

Criar o documento de Risco visando esclarecer os principais riscos que o projeto possa passar

**Tasks**
- [x] Listar riscos
- [x] Categorizar riscos
- [x] Definir as consequências de cada risco
- [x] Definir as contingências de cada risco
- [x] Criar tabela com estimativa de probabilidade e impacto de cada risco

**Critérios de aceitação:**
- [x] O documento consegue passar uma ideia completa sobre os riscos que circundam o projeto

**Comment by andrelucasf** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Amis-6360797e8fcdf43062d4d7b8/issues/fga-eps-mds/2022.2-Amis-Doc/50?planning-poker) with Zenhub @jps12 @thiagolsg @gabrielapivetta @fxred @Jvsoutomaior @CaioSulz @ItaloBrunoM @paulohborba @FabricioDeQueiroz @KalebeLopes
