### ISSUE TITLE
Configurar SonarQube para o frontend

### ISSUE THREAD

**Issue by andrelucasf** [fga-eps-mds/2022.2-Amis-Doc#55]
**Descrição:**

Aqui vc vai descrever o que tem para ser feito e um pouco do contexto da issue

**Tasks**
- [x] Configurar o SonarCube para atuar no repositório do frontend
- [x] Definir quais serão as metricas e testes a serem utilizados

**Critérios de aceitação:**
- [x] SonarCube roda testes automaticamente quando há commits na branch develop

**Comment by andrelucasf** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Amis-6360797e8fcdf43062d4d7b8/issues/fga-eps-mds/2022.2-Amis-Doc/55?planning-poker) with Zenhub @CaioSulz @FabricioDeQueiroz @fxred @gabrielapivetta @ItaloBrunoM @jps12 @Jvsoutomaior @KalebeLopes @paulohborba @thiagolsg

**Comment by jps12** [comment]
@andrelucasf @gabrielapivetta @thiagolsg @KalebeLopes Issue pronta para revisão
