### ISSUE TITLE
Complemento Guia de Contribuição

### ISSUE THREAD

**Issue by CaioSulz** [fga-eps-mds/2022.2-Amis-Doc#57]
**Descrição:**

Adicionar tutorial para o pull request

**Tasks**
- [ ] Explicação do pull request
- [ ] Adição dos screenshots do pull request

**Critérios de aceitação:**
- [ ] Explicação em conceito e em imagem do pull request
