### ISSUE TITLE
Dojo de Git

### ISSUE THREAD

**Issue by gabrielapivetta** [fga-eps-mds/2022.2-Amis-Doc#6]
**Descrição:**

Aula introdutória sobre git e markdown para os alunos de MDS marcada para o dia 04/11/2022.

**Tasks**
- [x] Explicar conceitos de git
- [x] Mostrar como usar os comandos na prática
- [x] Criar issues
- [x] Criar branches
- [x] Fazer commits

**Critérios de aceitação**
- [x] Participação da maioria dos membros de MDS.
- [x] Gravar a reunião e disponibilizar o link

**Comment by gabrielapivetta** [comment]
Dojo realizado; Issue concluída.
