### ISSUE TITLE
Dojo de Metodologias Ágeis

### ISSUE THREAD

**Issue by gabrielapivetta** [fga-eps-mds/2022.2-Amis-Doc#8]
**Descrição:**
Ensinar sobre as metodologias ágeis para os membros de MDS.

**Tasks:**
- [x] Agendar horário para realização do dojo
- [x] Realizar o dojo presencialmente
- [x] Ensinar sobre o tema

**Critérios de aceitação:**

- [x] O dojo foi realizado presencialmente
- [x] Foram passados os principais conceitos das metodologias ágeis mais utilizadas

**Comment by gabrielapivetta** [comment]
Dojo realizado!
