### ISSUE TITLE
Evolução do Protótipo

### ISSUE THREAD

**Issue by andrelucasf** [fga-eps-mds/2022.2-Amis-Doc#90]
**Descrição:**

Alguns pontos de melhoria a respeito do protótipo que foram observados. 

**Tasks**
- [x] Adicionar link do protótipo as histórias de usuários
- [x] Documentar o protótipo completo (adicionar legenda nas telas validadas)
- [x] Adicionar documento de identidade visual (Já consta no figma)

**Critérios de aceitação:**
- [x] US com link das telas do protótipo
- [ ] Documento sem imagem estática (quadro interativo do Figma)

**Comment by jps12** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Amis-6360797e8fcdf43062d4d7b8/issues/fga-eps-mds/2022.2-Amis-Doc/90?planning-poker) with Zenhub @andrelucasf @CaioSulz @FabricioDeQueiroz @fxred @gabrielapivetta @ItaloBrunoM @Jvsoutomaior @KalebeLopes @paulohborba @thiagolsg
