### ISSUE TITLE
Evolução da Qualidade

### ISSUE THREAD

**Issue by gabrielapivetta** [fga-eps-mds/2022.2-Amis-Doc#91]
**Descrição:**

Evolução do Documento de Qualidade pós Release 1.

**Tasks**
- [x] Tornar o texto menos genérico
- [x] Alterar o texto para ISO 251010

**Critérios de aceitação:**
- [x] Tornar imagens ou markdown estáticos em planilha dinâmica, caso exista.
- [x] Terminar as tasks

**Comment by jps12** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Amis-6360797e8fcdf43062d4d7b8/issues/fga-eps-mds/2022.2-Amis-Doc/91?planning-poker) with Zenhub @andrelucasf @CaioSulz @FabricioDeQueiroz @fxred @gabrielapivetta @ItaloBrunoM @Jvsoutomaior @KalebeLopes @paulohborba @thiagolsg
