### ISSUE TITLE
Configuração do ambiente de testes Front-End

### ISSUE THREAD

**Issue by KalebeLopes** [fga-eps-mds/2022.2-Amis-Doc#92]
**Descrição:**

Criação de testes

**Tasks**
- [ ] Teste de código no frontend
- [ ] Teste Funcional
- [ ] Configurar métricas de execução de testes (SONARQUBE)
- [ ] Extrair métricas de execução de testes (SONARQUBE)

**Critérios de aceitação:**
- [ ] Testes passando
- [ ] SONARQUBE configurado e métricas extraídas

**Comment by jps12** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Amis-6360797e8fcdf43062d4d7b8/issues/fga-eps-mds/2022.2-Amis-Doc/92?planning-poker) with Zenhub @andrelucasf @CaioSulz @FabricioDeQueiroz @fxred @gabrielapivetta @ItaloBrunoM @Jvsoutomaior @KalebeLopes @paulohborba @thiagolsg

**Comment by jps12** [comment]
Foi necessário a instalação das ferramentas de teste no frontend para para execução dos testes. Para a instlação e configuração desse ambiente foram usados os seguintes tutoriais:
https://dev.to/theandersonn/configurando-o-jest-e-testing-library-no-vite-10p1
https://dev.to/dxwebster/pt-br-parte-2-hands-on-como-implementar-testes-unitarios-no-react-25jg

**Comment by jps12** [comment]
https://dev.to/alexeagleson/how-to-create-and-publish-a-react-component-library-2oe

Dica de link sobre como configurar os testes no front
