### ISSUE TITLE
Evolução do Roadmap e Backlog

### ISSUE THREAD

**Issue by andrelucasf** [fga-eps-mds/2022.2-Amis-Doc#93]
**Descrição:**

Alguns pontos de melhoria a respeito do roadmap e do backlog que foram observados.

**Tasks**

- [ ] Adicionar ao Roadmap tarefas realizadas no período anterior ao dia 5/12
- [ ] Realizar a estimativa de tempo das funcionalidades e estimativa por pontos do Backlog
- [ ] Adicionar critérios de aceitação de cada US no backlog
- [ ] Atualizar o MVP do Mural (Consta o cronograma do MVP e não do projeto)
- [ ] Fazer documento do escopo das releases
- [ ] EAP está incoerente ao Roadmap (ZenHub)

**Critérios de aceitação:**
- [ ] Tornar imagens ou markdown estáticos em planilha dinâmica, caso exista.
- [ ] Finalizar todas as tasks

**Comment by jps12** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Amis-6360797e8fcdf43062d4d7b8/issues/fga-eps-mds/2022.2-Amis-Doc/93?planning-poker) with Zenhub @andrelucasf @CaioSulz @FabricioDeQueiroz @fxred @gabrielapivetta @ItaloBrunoM @Jvsoutomaior @KalebeLopes @paulohborba @thiagolsg
