### ISSUE TITLE
Evolução de Custo

### ISSUE THREAD

**Issue by gabrielapivetta** [fga-eps-mds/2022.2-Amis-Doc#94]
**Descrição:**

Evolução dos Documentos de Custo, pós Release 1.

**Tasks**
- [x] Corrigir o documento de custo com base nas 16 semanas
- [x] Atualizar o planilha de custo e cálculos
- [x] Detalhar e explicar os valores do custo

**Critérios de aceitação:**
- [x] Tornar imagens ou markdown estáticos em planilha dinâmica, caso exista.
- [x] Terminar as tasks

**Comment by jps12** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Amis-6360797e8fcdf43062d4d7b8/issues/fga-eps-mds/2022.2-Amis-Doc/94?planning-poker) with Zenhub @andrelucasf @CaioSulz @FabricioDeQueiroz @fxred @gabrielapivetta @ItaloBrunoM @Jvsoutomaior @KalebeLopes @paulohborba @thiagolsg
