### ISSUE TITLE
Evolução da Arquitetura

### ISSUE THREAD

**Issue by andrelucasf** [fga-eps-mds/2022.2-Amis-Doc#95]
**Descrição:**

Alguns pontos de melhoria a respeito do protótipo que foram observados.

**Tasks**
- [x] Modularizar em microsserviços
- [x] Diagrama de caso de uso errado, está um diagrama representando as histórias

**Critérios de aceitação:**
- [x] Tornar imagens ou markdown estáticos em planilha dinâmica, caso exista.

**Comment by jps12** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Amis-6360797e8fcdf43062d4d7b8/issues/fga-eps-mds/2022.2-Amis-Doc/95?planning-poker) with Zenhub @andrelucasf @CaioSulz @FabricioDeQueiroz @fxred @gabrielapivetta @ItaloBrunoM @Jvsoutomaior @KalebeLopes @paulohborba @thiagolsg
