### ISSUE TITLE
Evolução do Quadro de conhecimento

### ISSUE THREAD

**Issue by KalebeLopes** [fga-eps-mds/2022.2-Amis-Doc#96]
**Descrição:**

Evolução do quadro de conhecimentos

**Tasks**
- [x] Criar uma nova página do quadro de disponibilidade de horários para a release 2
- [x] Criar uma nova página do quadro de disponibilidade de conhecimentos
- [x] Adicionar legenda no quadro de conhecimentos

**Critérios de aceitação:**
- [x] Nova página criada
- [x] Terminar as tasks

**Comment by jps12** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Amis-6360797e8fcdf43062d4d7b8/issues/fga-eps-mds/2022.2-Amis-Doc/96?planning-poker) with Zenhub @andrelucasf @CaioSulz @FabricioDeQueiroz @fxred @gabrielapivetta @ItaloBrunoM @Jvsoutomaior @KalebeLopes @paulohborba @thiagolsg
