### ISSUE TITLE
Evolução dos documentos em geral

### ISSUE THREAD

**Issue by KalebeLopes** [fga-eps-mds/2022.2-Amis-Doc#97]
**Descrição:**

Evolução dos documentos em geral

**Tasks**
- [x] Atualizar o dia da Planning/Review no documento de Plano de Comunicação
- [x] Documentar as validações das histórias
- [x] Disponibilizar links de homologação para o usuário
- [x] Gerar tags de release
- [x] Transformar todos os arquivos estáticos em planilhas

**Critérios de aceitação:**
- [x] Terminar todas as tasks

**Comment by jps12** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Amis-6360797e8fcdf43062d4d7b8/issues/fga-eps-mds/2022.2-Amis-Doc/97?planning-poker) with Zenhub @andrelucasf @CaioSulz @FabricioDeQueiroz @fxred @gabrielapivetta @ItaloBrunoM @Jvsoutomaior @KalebeLopes @paulohborba @thiagolsg

**Comment by gabrielapivetta** [comment]
A documentação das validações das histórias de usuário foi feita nas issues de cada US.
